-- Operation-event notification types + deep-link target.
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SALE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SALE_CANCELLED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SALE_RETURN';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'PURCHASE_ORDER';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'GOODS_RECEIVED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'PURCHASE_RETURN';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SUPPLIER_PAYMENT';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'STOCK_ADJUSTMENT';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'EXPENSE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'CUSTOMER_PAYMENT';

ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "href" TEXT;
